"""create all missing tools tables

Revision ID: d736e0c40d88
Revises: 665b6244e7c3
Create Date: 2026-02-26 15:46:24.433703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd736e0c40d88'
down_revision = '665b6244e7c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'DELETED', 'APPROVED', 'REJECTED', 'COMMENTED', 'ASSIGNED', 'COMPLETED', 'STATUS_CHANGED', name='activityaction'), nullable=False),
    sa.Column('entity_type', sa.Enum('ASSET', 'CHANGE_REQUEST', 'INITIATIVE', 'BUSINESS_GOAL', 'TASK', 'VENDOR', 'SLA', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_index(op.f('ix_activity_logs_activity_id'), 'activity_logs', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('key_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('ASSET', 'CHANGE_REQUEST', 'INITIATIVE', 'BUSINESS_GOAL', 'TASK', 'VENDOR', 'SLA', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('mentioned_users', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.comment_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_index(op.f('ix_comments_comment_id'), 'comments', ['comment_id'], unique=False)
    op.create_index(op.f('ix_comments_entity_id'), 'comments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_comments_entity_type'), 'comments', ['entity_type'], unique=False)
    op.create_table('governance_policies',
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('policy_name', sa.String(length=200), nullable=False),
    sa.Column('policy_type', sa.Enum('NAMING_CONVENTION', 'DOCUMENTATION', 'OWNERSHIP', 'DATA_CLASSIFICATION', 'SLA_REQUIREMENT', 'SECURITY_SCAN', 'SCHEMA_VALIDATION', 'QUALITY_THRESHOLD', name='policytype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('policy_definition', sa.JSON(), nullable=False),
    sa.Column('is_blocking', sa.Boolean(), nullable=True),
    sa.Column('enforcement_level', sa.String(length=50), nullable=True),
    sa.Column('applies_to_domains', sa.JSON(), nullable=True),
    sa.Column('applies_to_environments', sa.JSON(), nullable=True),
    sa.Column('exemption_allowed', sa.Boolean(), nullable=True),
    sa.Column('exemption_requires_approval', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('policy_id'),
    sa.UniqueConstraint('policy_name')
    )
    op.create_index(op.f('ix_governance_policies_policy_id'), 'governance_policies', ['policy_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('job_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('import_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('itsm_configurations',
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('system_type', sa.Enum('SERVICENOW', 'JIRA', name='itsmsystem'), nullable=False),
    sa.Column('instance_name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('api_endpoint', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('api_token_encrypted', sa.Text(), nullable=True),
    sa.Column('oauth_config', sa.JSON(), nullable=True),
    sa.Column('sync_enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_direction', sa.Enum('TO_ITSM', 'FROM_ITSM', 'BIDIRECTIONAL', name='syncdirection'), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('next_sync_at', sa.DateTime(), nullable=True),
    sa.Column('field_mappings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('config_id')
    )
    op.create_index(op.f('ix_itsm_configurations_config_id'), 'itsm_configurations', ['config_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('TASK_ASSIGNED', 'TASK_UPDATED', 'TASK_COMPLETED', 'APPROVAL_NEEDED', 'APPROVAL_APPROVED', 'APPROVAL_REJECTED', 'VIOLATION_DETECTED', 'SLA_BREACH', 'COMMENT_MENTION', 'COMMENT_REPLY', 'ASSET_UPDATED', 'INITIATIVE_MILESTONE', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('entity_type', sa.Enum('ASSET', 'CHANGE_REQUEST', 'INITIATIVE', 'BUSINESS_GOAL', 'TASK', 'VENDOR', 'SLA', name='entitytype'), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_id'), 'notifications', ['notification_id'], unique=False)
    op.create_index(op.f('ix_notifications_read'), 'notifications', ['read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('webhook_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('webhook_id')
    )
    op.create_table('itsm_record_mappings',
    sa.Column('mapping_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('itsm_record_type', sa.String(length=50), nullable=False),
    sa.Column('itsm_record_id', sa.String(length=100), nullable=False),
    sa.Column('itsm_record_number', sa.String(length=50), nullable=True),
    sa.Column('itsm_record_url', sa.String(length=500), nullable=True),
    sa.Column('sync_direction', sa.Enum('TO_ITSM', 'FROM_ITSM', 'BIDIRECTIONAL', name='syncdirection'), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CONFLICT', name='syncstatus'), nullable=False),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('portal_version', sa.Integer(), nullable=False),
    sa.Column('itsm_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['itsm_configurations.config_id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_index(op.f('ix_itsm_record_mappings_config_id'), 'itsm_record_mappings', ['config_id'], unique=False)
    op.create_index(op.f('ix_itsm_record_mappings_entity_id'), 'itsm_record_mappings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_itsm_record_mappings_entity_type'), 'itsm_record_mappings', ['entity_type'], unique=False)
    op.create_index(op.f('ix_itsm_record_mappings_itsm_record_id'), 'itsm_record_mappings', ['itsm_record_id'], unique=False)
    op.create_index(op.f('ix_itsm_record_mappings_mapping_id'), 'itsm_record_mappings', ['mapping_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('delivery_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.webhook_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('delivery_id')
    )
    op.create_table('data_lineage_nodes',
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.Enum('SOURCE', 'TABLE', 'VIEW', 'TRANSFORMATION', 'ANALYTICS', 'API', 'FILE', 'STREAM', name='lineagenodetype'), nullable=False),
    sa.Column('node_name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=1000), nullable=True),
    sa.Column('schema_definition', sa.JSON(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index(op.f('ix_data_lineage_nodes_node_id'), 'data_lineage_nodes', ['node_id'], unique=False)
    op.create_index(op.f('ix_data_lineage_nodes_node_name'), 'data_lineage_nodes', ['node_name'], unique=False)
    op.create_table('data_quality_rules',
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('table_name', sa.String(length=200), nullable=True),
    sa.Column('column_name', sa.String(length=200), nullable=True),
    sa.Column('quality_dimension', sa.Enum('COMPLETENESS', 'ACCURACY', 'CONSISTENCY', 'TIMELINESS', 'VALIDITY', 'UNIQUENESS', name='qualitydimension'), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=True),
    sa.Column('rule_definition', sa.Text(), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('threshold_operator', sa.String(length=10), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='qualityruleseverity'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('alert_on_failure', sa.Boolean(), nullable=True),
    sa.Column('alert_channels', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_index(op.f('ix_data_quality_rules_rule_id'), 'data_quality_rules', ['rule_id'], unique=False)
    op.create_table('impact_analysis_runs',
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=100), nullable=True),
    sa.Column('change_description', sa.Text(), nullable=True),
    sa.Column('impact_score', sa.String(length=20), nullable=True),
    sa.Column('upstream_dependencies_count', sa.Integer(), nullable=True),
    sa.Column('downstream_dependencies_count', sa.Integer(), nullable=True),
    sa.Column('affected_assets', sa.JSON(), nullable=True),
    sa.Column('affected_pipelines', sa.JSON(), nullable=True),
    sa.Column('affected_reports', sa.JSON(), nullable=True),
    sa.Column('affected_users_count', sa.Integer(), nullable=True),
    sa.Column('affected_teams', sa.JSON(), nullable=True),
    sa.Column('migration_required', sa.Boolean(), nullable=True),
    sa.Column('estimated_migration_hours', sa.Float(), nullable=True),
    sa.Column('recommended_actions', sa.JSON(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('analyzed_by', sa.Integer(), nullable=True),
    sa.Column('analysis_depth', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_impact_analysis_runs_analysis_id'), 'impact_analysis_runs', ['analysis_id'], unique=False)
    op.create_table('integration_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('integration_type', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('itsm_sync_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('mapping_id', sa.Integer(), nullable=True),
    sa.Column('sync_direction', sa.Enum('TO_ITSM', 'FROM_ITSM', 'BIDIRECTIONAL', name='syncdirection'), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CONFLICT', name='syncstatus'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('itsm_record_type', sa.String(length=50), nullable=False),
    sa.Column('itsm_record_id', sa.String(length=100), nullable=True),
    sa.Column('fields_changed', sa.JSON(), nullable=True),
    sa.Column('before_values', sa.JSON(), nullable=True),
    sa.Column('after_values', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('http_response_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_id'], ['itsm_configurations.config_id'], ),
    sa.ForeignKeyConstraint(['mapping_id'], ['itsm_record_mappings.mapping_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_itsm_sync_logs_config_id'), 'itsm_sync_logs', ['config_id'], unique=False)
    op.create_index(op.f('ix_itsm_sync_logs_log_id'), 'itsm_sync_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_itsm_sync_logs_mapping_id'), 'itsm_sync_logs', ['mapping_id'], unique=False)
    op.create_index(op.f('ix_itsm_sync_logs_started_at'), 'itsm_sync_logs', ['started_at'], unique=False)
    op.create_table('policy_validations',
    sa.Column('validation_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_name', sa.String(length=500), nullable=True),
    sa.Column('pipeline_id', sa.String(length=200), nullable=True),
    sa.Column('commit_sha', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('triggered_by', sa.String(length=200), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('violations', sa.JSON(), nullable=True),
    sa.Column('deployment_blocked', sa.Boolean(), nullable=True),
    sa.Column('exemption_requested', sa.Boolean(), nullable=True),
    sa.Column('exemption_approved', sa.Boolean(), nullable=True),
    sa.Column('exemption_approver', sa.Integer(), nullable=True),
    sa.Column('exemption_reason', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['exemption_approver'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['governance_policies.policy_id'], ),
    sa.PrimaryKeyConstraint('validation_id')
    )
    op.create_index(op.f('ix_policy_validations_validation_id'), 'policy_validations', ['validation_id'], unique=False)
    op.create_table('schema_registry',
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('schema_format', sa.Enum('AVRO', 'JSON_SCHEMA', 'PROTOBUF', 'PARQUET', 'SQL_DDL', name='schemaformat'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_definition', sa.JSON(), nullable=False),
    sa.Column('compatibility_mode', sa.Enum('BACKWARD', 'FORWARD', 'FULL', 'NONE', name='schemacompatibility'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_latest', sa.Boolean(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(), nullable=True),
    sa.Column('deprecated_reason', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.PrimaryKeyConstraint('schema_id')
    )
    op.create_index(op.f('ix_schema_registry_schema_id'), 'schema_registry', ['schema_id'], unique=False)
    op.create_index(op.f('ix_schema_registry_subject'), 'schema_registry', ['subject'], unique=False)
    op.create_table('sla_monitoring',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('metric_type', sa.Enum('AVAILABILITY', 'PERFORMANCE', 'RELIABILITY', 'FRESHNESS', 'CAPACITY', name='slametrictype'), nullable=False),
    sa.Column('metric_name', sa.String(length=200), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('target_unit', sa.String(length=50), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('measurement_timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_within_sla', sa.Boolean(), nullable=True),
    sa.Column('deviation_percentage', sa.Float(), nullable=True),
    sa.Column('metric_source', sa.String(length=100), nullable=True),
    sa.Column('collection_method', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_sla_monitoring_measurement_timestamp'), 'sla_monitoring', ['measurement_timestamp'], unique=False)
    op.create_index(op.f('ix_sla_monitoring_metric_id'), 'sla_monitoring', ['metric_id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('initiative_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='taskpriority'), nullable=False),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'BLOCKED', 'DONE', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('actual_hours', sa.Integer(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['initiative_id'], ['strategic_initiatives.initiative_id'], ),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=False)
    op.create_table('data_lineage_edges',
    sa.Column('edge_id', sa.Integer(), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('transformation_type', sa.Enum('EXTRACT', 'TRANSFORM', 'LOAD', 'AGGREGATE', 'JOIN', 'FILTER', 'ENRICH', 'ANONYMIZE', 'CUSTOM', name='transformationtype'), nullable=False),
    sa.Column('transformation_logic', sa.Text(), nullable=True),
    sa.Column('transformation_tool', sa.String(length=200), nullable=True),
    sa.Column('column_mappings', sa.JSON(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('rows_processed', sa.Integer(), nullable=True),
    sa.Column('bytes_processed', sa.Integer(), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['data_lineage_nodes.node_id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['data_lineage_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index(op.f('ix_data_lineage_edges_edge_id'), 'data_lineage_edges', ['edge_id'], unique=False)
    op.create_index(op.f('ix_data_lineage_edges_source_node_id'), 'data_lineage_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_data_lineage_edges_target_node_id'), 'data_lineage_edges', ['target_node_id'], unique=False)
    op.create_table('quality_check_runs',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time_seconds', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('violation_count', sa.Integer(), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sample_violations', sa.JSON(), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.Column('alert_sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['data_quality_rules.rule_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_quality_check_runs_rule_id'), 'quality_check_runs', ['rule_id'], unique=False)
    op.create_index(op.f('ix_quality_check_runs_run_id'), 'quality_check_runs', ['run_id'], unique=False)
    op.create_table('schema_validations',
    sa.Column('validation_id', sa.Integer(), nullable=False),
    sa.Column('schema_id', sa.Integer(), nullable=False),
    sa.Column('validation_type', sa.String(length=100), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('validation_errors', sa.JSON(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schema_registry.schema_id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('validation_id')
    )
    op.create_table('sla_violations',
    sa.Column('violation_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('violated_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('deviation_percentage', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('impact_description', sa.Text(), nullable=True),
    sa.Column('affected_users_count', sa.Integer(), nullable=True),
    sa.Column('alert_sent', sa.Boolean(), nullable=True),
    sa.Column('alert_sent_at', sa.DateTime(), nullable=True),
    sa.Column('incident_created', sa.Boolean(), nullable=True),
    sa.Column('incident_id', sa.String(length=100), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('remediation_actions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['sla_monitoring.metric_id'], ),
    sa.PrimaryKeyConstraint('violation_id')
    )
    op.create_index(op.f('ix_sla_violations_violated_at'), 'sla_violations', ['violated_at'], unique=False)
    op.create_index(op.f('ix_sla_violations_violation_id'), 'sla_violations', ['violation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sla_violations_violation_id'), table_name='sla_violations')
    op.drop_index(op.f('ix_sla_violations_violated_at'), table_name='sla_violations')
    op.drop_table('sla_violations')
    op.drop_table('schema_validations')
    op.drop_index(op.f('ix_quality_check_runs_run_id'), table_name='quality_check_runs')
    op.drop_index(op.f('ix_quality_check_runs_rule_id'), table_name='quality_check_runs')
    op.drop_table('quality_check_runs')
    op.drop_index(op.f('ix_data_lineage_edges_target_node_id'), table_name='data_lineage_edges')
    op.drop_index(op.f('ix_data_lineage_edges_source_node_id'), table_name='data_lineage_edges')
    op.drop_index(op.f('ix_data_lineage_edges_edge_id'), table_name='data_lineage_edges')
    op.drop_table('data_lineage_edges')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_sla_monitoring_metric_id'), table_name='sla_monitoring')
    op.drop_index(op.f('ix_sla_monitoring_measurement_timestamp'), table_name='sla_monitoring')
    op.drop_table('sla_monitoring')
    op.drop_index(op.f('ix_schema_registry_subject'), table_name='schema_registry')
    op.drop_index(op.f('ix_schema_registry_schema_id'), table_name='schema_registry')
    op.drop_table('schema_registry')
    op.drop_index(op.f('ix_policy_validations_validation_id'), table_name='policy_validations')
    op.drop_table('policy_validations')
    op.drop_index(op.f('ix_itsm_sync_logs_started_at'), table_name='itsm_sync_logs')
    op.drop_index(op.f('ix_itsm_sync_logs_mapping_id'), table_name='itsm_sync_logs')
    op.drop_index(op.f('ix_itsm_sync_logs_log_id'), table_name='itsm_sync_logs')
    op.drop_index(op.f('ix_itsm_sync_logs_config_id'), table_name='itsm_sync_logs')
    op.drop_table('itsm_sync_logs')
    op.drop_table('integration_logs')
    op.drop_index(op.f('ix_impact_analysis_runs_analysis_id'), table_name='impact_analysis_runs')
    op.drop_table('impact_analysis_runs')
    op.drop_index(op.f('ix_data_quality_rules_rule_id'), table_name='data_quality_rules')
    op.drop_table('data_quality_rules')
    op.drop_index(op.f('ix_data_lineage_nodes_node_name'), table_name='data_lineage_nodes')
    op.drop_index(op.f('ix_data_lineage_nodes_node_id'), table_name='data_lineage_nodes')
    op.drop_table('data_lineage_nodes')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_itsm_record_mappings_mapping_id'), table_name='itsm_record_mappings')
    op.drop_index(op.f('ix_itsm_record_mappings_itsm_record_id'), table_name='itsm_record_mappings')
    op.drop_index(op.f('ix_itsm_record_mappings_entity_type'), table_name='itsm_record_mappings')
    op.drop_index(op.f('ix_itsm_record_mappings_entity_id'), table_name='itsm_record_mappings')
    op.drop_index(op.f('ix_itsm_record_mappings_config_id'), table_name='itsm_record_mappings')
    op.drop_table('itsm_record_mappings')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_itsm_configurations_config_id'), table_name='itsm_configurations')
    op.drop_table('itsm_configurations')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_governance_policies_policy_id'), table_name='governance_policies')
    op.drop_table('governance_policies')
    op.drop_index(op.f('ix_comments_entity_type'), table_name='comments')
    op.drop_index(op.f('ix_comments_entity_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_comment_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_activity_id'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
