"""add advanced governance features - lineage, quality, impact analysis

Revision ID: 335acad41467
Revises: 1cb7b5bc23d8
Create Date: 2026-02-22 02:37:19.164631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '335acad41467'
down_revision = '1cb7b5bc23d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
