"""create tools tables for postgresql

Revision ID: 665b6244e7c3
Revises: ca08a7e698c6
Create Date: 2026-02-26 15:42:14.964394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665b6244e7c3'
down_revision = 'ca08a7e698c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('value_delivered_metrics',
    sa.Column('metric_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('initiative_id', sa.Integer(), nullable=True),
    sa.Column('business_goal_id', sa.Integer(), nullable=True),
    sa.Column('metric_type', sa.String(length=50), nullable=True),
    sa.Column('value_delivered', sa.String(length=255), nullable=False),
    sa.Column('key_achievement', sa.Text(), nullable=False),
    sa.Column('measurement_date', sa.Date(), nullable=False),
    sa.Column('measurement_period', sa.String(length=50), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.Column('validated_by', sa.Integer(), nullable=True),
    sa.Column('validation_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['business_goal_id'], ['business_goals.goal_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.ForeignKeyConstraint(['initiative_id'], ['strategic_initiatives.initiative_id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_value_delivered_metrics_metric_id'), 'value_delivered_metrics', ['metric_id'], unique=False)
    op.add_column('business_goals', sa.Column('success_criteria', sa.Text(), nullable=True))
    op.add_column('business_goals', sa.Column('expected_roi', sa.Float(), nullable=True))
    op.add_column('business_goals', sa.Column('investment_amount', sa.Float(), nullable=True))
    op.add_column('business_goals', sa.Column('completion_percentage', sa.Integer(), nullable=True))
    op.add_column('initiative_deliverables', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'initiative_deliverables', 'users', ['assigned_to'], ['user_id'])
    op.add_column('strategic_initiatives', sa.Column('completion_percentage', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategic_initiatives', 'completion_percentage')
    op.drop_constraint(None, 'initiative_deliverables', type_='foreignkey')
    op.drop_column('initiative_deliverables', 'assigned_to')
    op.drop_column('business_goals', 'completion_percentage')
    op.drop_column('business_goals', 'investment_amount')
    op.drop_column('business_goals', 'expected_roi')
    op.drop_column('business_goals', 'success_criteria')
    op.drop_index(op.f('ix_value_delivered_metrics_metric_id'), table_name='value_delivered_metrics')
    op.drop_table('value_delivered_metrics')
    # ### end Alembic commands ###
