"""add phase 3 integration models - webhooks api_keys integrations

Revision ID: ca08a7e698c6
Revises: 335acad41467
Create Date: 2026-02-22 17:31:45.386685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'ca08a7e698c6'
down_revision = '335acad41467'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sla_monitoring_measurement_timestamp', table_name='sla_monitoring')
    op.drop_index('ix_sla_monitoring_metric_id', table_name='sla_monitoring')
    op.drop_table('sla_monitoring')
    op.drop_index('ix_data_lineage_nodes_node_id', table_name='data_lineage_nodes')
    op.drop_index('ix_data_lineage_nodes_node_name', table_name='data_lineage_nodes')
    op.drop_table('data_lineage_nodes')
    op.drop_index('ix_governance_policies_policy_id', table_name='governance_policies')
    op.drop_table('governance_policies')
    op.drop_index('ix_impact_analysis_runs_analysis_id', table_name='impact_analysis_runs')
    op.drop_table('impact_analysis_runs')
    op.drop_table('schema_validations')
    op.drop_index('ix_quality_check_runs_rule_id', table_name='quality_check_runs')
    op.drop_index('ix_quality_check_runs_run_id', table_name='quality_check_runs')
    op.drop_table('quality_check_runs')
    op.drop_index('ix_data_lineage_edges_edge_id', table_name='data_lineage_edges')
    op.drop_index('ix_data_lineage_edges_source_node_id', table_name='data_lineage_edges')
    op.drop_index('ix_data_lineage_edges_target_node_id', table_name='data_lineage_edges')
    op.drop_table('data_lineage_edges')
    op.drop_index('ix_data_quality_rules_rule_id', table_name='data_quality_rules')
    op.drop_table('data_quality_rules')
    op.drop_index('ix_sla_violations_violated_at', table_name='sla_violations')
    op.drop_index('ix_sla_violations_violation_id', table_name='sla_violations')
    op.drop_table('sla_violations')
    op.drop_index('ix_schema_registry_schema_id', table_name='schema_registry')
    op.drop_index('ix_schema_registry_subject', table_name='schema_registry')
    op.drop_table('schema_registry')
    op.drop_index('ix_policy_validations_validation_id', table_name='policy_validations')
    op.drop_table('policy_validations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policy_validations',
    sa.Column('validation_id', sa.INTEGER(), nullable=False),
    sa.Column('policy_id', sa.INTEGER(), nullable=False),
    sa.Column('asset_id', sa.INTEGER(), nullable=True),
    sa.Column('asset_name', sa.VARCHAR(length=500), nullable=True),
    sa.Column('pipeline_id', sa.VARCHAR(length=200), nullable=True),
    sa.Column('commit_sha', sa.VARCHAR(length=100), nullable=True),
    sa.Column('branch', sa.VARCHAR(length=200), nullable=True),
    sa.Column('triggered_by', sa.VARCHAR(length=200), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=False),
    sa.Column('violations', sqlite.JSON(), nullable=True),
    sa.Column('deployment_blocked', sa.BOOLEAN(), nullable=True),
    sa.Column('exemption_requested', sa.BOOLEAN(), nullable=True),
    sa.Column('exemption_approved', sa.BOOLEAN(), nullable=True),
    sa.Column('exemption_approver', sa.INTEGER(), nullable=True),
    sa.Column('exemption_reason', sa.TEXT(), nullable=True),
    sa.Column('validated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['exemption_approver'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['governance_policies.policy_id'], ),
    sa.PrimaryKeyConstraint('validation_id')
    )
    op.create_index('ix_policy_validations_validation_id', 'policy_validations', ['validation_id'], unique=False)
    op.create_table('schema_registry',
    sa.Column('schema_id', sa.INTEGER(), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), nullable=False),
    sa.Column('schema_format', sa.VARCHAR(length=11), nullable=False),
    sa.Column('version', sa.INTEGER(), nullable=False),
    sa.Column('schema_definition', sqlite.JSON(), nullable=False),
    sa.Column('compatibility_mode', sa.VARCHAR(length=8), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_latest', sa.BOOLEAN(), nullable=True),
    sa.Column('asset_id', sa.INTEGER(), nullable=True),
    sa.Column('domain_id', sa.INTEGER(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('deprecated_at', sa.DATETIME(), nullable=True),
    sa.Column('deprecated_reason', sa.TEXT(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('changelog', sa.TEXT(), nullable=True),
    sa.Column('examples', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.PrimaryKeyConstraint('schema_id')
    )
    op.create_index('ix_schema_registry_subject', 'schema_registry', ['subject'], unique=False)
    op.create_index('ix_schema_registry_schema_id', 'schema_registry', ['schema_id'], unique=False)
    op.create_table('sla_violations',
    sa.Column('violation_id', sa.INTEGER(), nullable=False),
    sa.Column('metric_id', sa.INTEGER(), nullable=False),
    sa.Column('violated_at', sa.DATETIME(), nullable=False),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=True),
    sa.Column('target_value', sa.FLOAT(), nullable=True),
    sa.Column('actual_value', sa.FLOAT(), nullable=True),
    sa.Column('deviation_percentage', sa.FLOAT(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=True),
    sa.Column('impact_description', sa.TEXT(), nullable=True),
    sa.Column('affected_users_count', sa.INTEGER(), nullable=True),
    sa.Column('alert_sent', sa.BOOLEAN(), nullable=True),
    sa.Column('alert_sent_at', sa.DATETIME(), nullable=True),
    sa.Column('incident_created', sa.BOOLEAN(), nullable=True),
    sa.Column('incident_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('root_cause', sa.TEXT(), nullable=True),
    sa.Column('remediation_actions', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['metric_id'], ['sla_monitoring.metric_id'], ),
    sa.PrimaryKeyConstraint('violation_id')
    )
    op.create_index('ix_sla_violations_violation_id', 'sla_violations', ['violation_id'], unique=False)
    op.create_index('ix_sla_violations_violated_at', 'sla_violations', ['violated_at'], unique=False)
    op.create_table('data_quality_rules',
    sa.Column('rule_id', sa.INTEGER(), nullable=False),
    sa.Column('rule_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('asset_id', sa.INTEGER(), nullable=True),
    sa.Column('table_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('column_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('quality_dimension', sa.VARCHAR(length=12), nullable=False),
    sa.Column('rule_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('rule_definition', sa.TEXT(), nullable=False),
    sa.Column('threshold_value', sa.FLOAT(), nullable=True),
    sa.Column('threshold_operator', sa.VARCHAR(length=10), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=8), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('schedule', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_run', sa.DATETIME(), nullable=True),
    sa.Column('next_run', sa.DATETIME(), nullable=True),
    sa.Column('alert_on_failure', sa.BOOLEAN(), nullable=True),
    sa.Column('alert_channels', sqlite.JSON(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rule_id'),
    sa.UniqueConstraint('rule_name')
    )
    op.create_index('ix_data_quality_rules_rule_id', 'data_quality_rules', ['rule_id'], unique=False)
    op.create_table('data_lineage_edges',
    sa.Column('edge_id', sa.INTEGER(), nullable=False),
    sa.Column('source_node_id', sa.INTEGER(), nullable=False),
    sa.Column('target_node_id', sa.INTEGER(), nullable=False),
    sa.Column('transformation_type', sa.VARCHAR(length=9), nullable=False),
    sa.Column('transformation_logic', sa.TEXT(), nullable=True),
    sa.Column('transformation_tool', sa.VARCHAR(length=200), nullable=True),
    sa.Column('column_mappings', sqlite.JSON(), nullable=True),
    sa.Column('execution_time_seconds', sa.FLOAT(), nullable=True),
    sa.Column('rows_processed', sa.INTEGER(), nullable=True),
    sa.Column('bytes_processed', sa.INTEGER(), nullable=True),
    sa.Column('schedule', sa.VARCHAR(length=100), nullable=True),
    sa.Column('last_run', sa.DATETIME(), nullable=True),
    sa.Column('next_run', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['data_lineage_nodes.node_id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['data_lineage_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index('ix_data_lineage_edges_target_node_id', 'data_lineage_edges', ['target_node_id'], unique=False)
    op.create_index('ix_data_lineage_edges_source_node_id', 'data_lineage_edges', ['source_node_id'], unique=False)
    op.create_index('ix_data_lineage_edges_edge_id', 'data_lineage_edges', ['edge_id'], unique=False)
    op.create_table('quality_check_runs',
    sa.Column('run_id', sa.INTEGER(), nullable=False),
    sa.Column('rule_id', sa.INTEGER(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=False),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('execution_time_seconds', sa.FLOAT(), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=False),
    sa.Column('actual_value', sa.FLOAT(), nullable=True),
    sa.Column('threshold_value', sa.FLOAT(), nullable=True),
    sa.Column('violation_count', sa.INTEGER(), nullable=True),
    sa.Column('total_count', sa.INTEGER(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('sample_violations', sqlite.JSON(), nullable=True),
    sa.Column('alert_sent', sa.BOOLEAN(), nullable=True),
    sa.Column('alert_sent_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['data_quality_rules.rule_id'], ),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index('ix_quality_check_runs_run_id', 'quality_check_runs', ['run_id'], unique=False)
    op.create_index('ix_quality_check_runs_rule_id', 'quality_check_runs', ['rule_id'], unique=False)
    op.create_table('schema_validations',
    sa.Column('validation_id', sa.INTEGER(), nullable=False),
    sa.Column('schema_id', sa.INTEGER(), nullable=False),
    sa.Column('validation_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_valid', sa.BOOLEAN(), nullable=False),
    sa.Column('validation_errors', sqlite.JSON(), nullable=True),
    sa.Column('validated_at', sa.DATETIME(), nullable=True),
    sa.Column('validated_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['schema_id'], ['schema_registry.schema_id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('validation_id')
    )
    op.create_table('impact_analysis_runs',
    sa.Column('analysis_id', sa.INTEGER(), nullable=False),
    sa.Column('asset_id', sa.INTEGER(), nullable=False),
    sa.Column('change_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('change_description', sa.TEXT(), nullable=True),
    sa.Column('impact_score', sa.VARCHAR(length=20), nullable=True),
    sa.Column('upstream_dependencies_count', sa.INTEGER(), nullable=True),
    sa.Column('downstream_dependencies_count', sa.INTEGER(), nullable=True),
    sa.Column('affected_assets', sqlite.JSON(), nullable=True),
    sa.Column('affected_pipelines', sqlite.JSON(), nullable=True),
    sa.Column('affected_reports', sqlite.JSON(), nullable=True),
    sa.Column('affected_users_count', sa.INTEGER(), nullable=True),
    sa.Column('affected_teams', sqlite.JSON(), nullable=True),
    sa.Column('migration_required', sa.BOOLEAN(), nullable=True),
    sa.Column('estimated_migration_hours', sa.FLOAT(), nullable=True),
    sa.Column('recommended_actions', sqlite.JSON(), nullable=True),
    sa.Column('rollback_plan', sa.TEXT(), nullable=True),
    sa.Column('analyzed_at', sa.DATETIME(), nullable=True),
    sa.Column('analyzed_by', sa.INTEGER(), nullable=True),
    sa.Column('analysis_depth', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['analyzed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index('ix_impact_analysis_runs_analysis_id', 'impact_analysis_runs', ['analysis_id'], unique=False)
    op.create_table('governance_policies',
    sa.Column('policy_id', sa.INTEGER(), nullable=False),
    sa.Column('policy_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('policy_type', sa.VARCHAR(length=19), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('policy_definition', sqlite.JSON(), nullable=False),
    sa.Column('is_blocking', sa.BOOLEAN(), nullable=True),
    sa.Column('enforcement_level', sa.VARCHAR(length=50), nullable=True),
    sa.Column('applies_to_domains', sqlite.JSON(), nullable=True),
    sa.Column('applies_to_environments', sqlite.JSON(), nullable=True),
    sa.Column('exemption_allowed', sa.BOOLEAN(), nullable=True),
    sa.Column('exemption_requires_approval', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('policy_id'),
    sa.UniqueConstraint('policy_name')
    )
    op.create_index('ix_governance_policies_policy_id', 'governance_policies', ['policy_id'], unique=False)
    op.create_table('data_lineage_nodes',
    sa.Column('node_id', sa.INTEGER(), nullable=False),
    sa.Column('asset_id', sa.INTEGER(), nullable=True),
    sa.Column('node_type', sa.VARCHAR(length=14), nullable=False),
    sa.Column('node_name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('location', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('schema_definition', sqlite.JSON(), nullable=True),
    sa.Column('row_count', sa.INTEGER(), nullable=True),
    sa.Column('size_bytes', sa.INTEGER(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('domain_id', sa.INTEGER(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_index('ix_data_lineage_nodes_node_name', 'data_lineage_nodes', ['node_name'], unique=False)
    op.create_index('ix_data_lineage_nodes_node_id', 'data_lineage_nodes', ['node_id'], unique=False)
    op.create_table('sla_monitoring',
    sa.Column('metric_id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.Column('asset_id', sa.INTEGER(), nullable=True),
    sa.Column('metric_type', sa.VARCHAR(length=12), nullable=False),
    sa.Column('metric_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('target_value', sa.FLOAT(), nullable=False),
    sa.Column('target_unit', sa.VARCHAR(length=50), nullable=True),
    sa.Column('current_value', sa.FLOAT(), nullable=True),
    sa.Column('measurement_timestamp', sa.DATETIME(), nullable=False),
    sa.Column('is_within_sla', sa.BOOLEAN(), nullable=True),
    sa.Column('deviation_percentage', sa.FLOAT(), nullable=True),
    sa.Column('metric_source', sa.VARCHAR(length=100), nullable=True),
    sa.Column('collection_method', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index('ix_sla_monitoring_metric_id', 'sla_monitoring', ['metric_id'], unique=False)
    op.create_index('ix_sla_monitoring_measurement_timestamp', 'sla_monitoring', ['measurement_timestamp'], unique=False)
    # ### end Alembic commands ###
