"""initial schema

Revision ID: 1cb7b5bc23d8
Revises: 
Create Date: 2026-02-22 02:19:14.720126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb7b5bc23d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compliance_metrics',
    sa.Column('metric_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_assets', sa.Integer(), nullable=True),
    sa.Column('compliant_assets', sa.Integer(), nullable=True),
    sa.Column('compliance_rate', sa.Integer(), nullable=True),
    sa.Column('missing_documentation', sa.Integer(), nullable=True),
    sa.Column('version_conflicts', sa.Integer(), nullable=True),
    sa.Column('pending_changes', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_compliance_metrics_metric_date'), 'compliance_metrics', ['metric_date'], unique=False)
    op.create_index(op.f('ix_compliance_metrics_metric_id'), 'compliance_metrics', ['metric_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_index(op.f('ix_roles_role_id'), 'roles', ['role_id'], unique=False)
    op.create_table('stakeholders',
    sa.Column('stakeholder_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('influence_level', sa.String(length=20), nullable=True),
    sa.Column('engagement_level', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('stakeholder_id')
    )
    op.create_index(op.f('ix_stakeholders_stakeholder_id'), 'stakeholders', ['stakeholder_id'], unique=False)
    op.create_table('vendors',
    sa.Column('vendor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('vendor_type', sa.String(length=100), nullable=True),
    sa.Column('contact_name', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('contract_start', sa.Date(), nullable=True),
    sa.Column('contract_end', sa.Date(), nullable=True),
    sa.Column('annual_cost', sa.Float(), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('performance_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('vendor_id')
    )
    op.create_index(op.f('ix_vendors_vendor_id'), 'vendors', ['vendor_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vendor_slas',
    sa.Column('sla_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('sla_metric', sa.String(length=255), nullable=True),
    sa.Column('target_value', sa.String(length=100), nullable=True),
    sa.Column('current_value', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('measurement_period', sa.String(length=50), nullable=True),
    sa.Column('last_measured', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('sla_id')
    )
    op.create_index(op.f('ix_vendor_slas_sla_id'), 'vendor_slas', ['sla_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('business_goals',
    sa.Column('goal_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('goal_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('kpi_metric', sa.String(length=255), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_index(op.f('ix_business_goals_goal_id'), 'business_goals', ['goal_id'], unique=False)
    op.create_table('domains',
    sa.Column('domain_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain_code', sa.String(length=10), nullable=False),
    sa.Column('domain_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_steward_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['data_steward_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('domain_id'),
    sa.UniqueConstraint('domain_code')
    )
    op.create_index(op.f('ix_domains_domain_id'), 'domains', ['domain_id'], unique=False)
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=10), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('lifecycle_stage', sa.String(length=20), nullable=False),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('naming_compliant', sa.Boolean(), nullable=True),
    sa.Column('compliance_check_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("environment IN ('DEV', 'QA', 'PROD', 'UAT')", name='check_environment'),
    sa.CheckConstraint("lifecycle_stage IN ('Draft', 'Active', 'Deprecated', 'Retired')", name='check_lifecycle'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('asset_id')
    )
    op.create_index(op.f('ix_assets_asset_id'), 'assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_assets_asset_name'), 'assets', ['asset_name'], unique=True)
    op.create_index(op.f('ix_assets_naming_compliant'), 'assets', ['naming_compliant'], unique=False)
    op.create_table('budget_allocations',
    sa.Column('budget_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('allocated_amount', sa.Float(), nullable=False),
    sa.Column('spent_amount', sa.Float(), nullable=True),
    sa.Column('forecasted_spend', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domains.domain_id'], ),
    sa.PrimaryKeyConstraint('budget_id')
    )
    op.create_index(op.f('ix_budget_allocations_budget_id'), 'budget_allocations', ['budget_id'], unique=False)
    op.create_table('strategic_initiatives',
    sa.Column('initiative_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('initiative_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_goal_id', sa.Integer(), nullable=True),
    sa.Column('initiative_lead_id', sa.Integer(), nullable=True),
    sa.Column('budget_allocated', sa.Float(), nullable=True),
    sa.Column('budget_spent', sa.Float(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('expected_roi', sa.Float(), nullable=True),
    sa.Column('stakeholder_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['business_goal_id'], ['business_goals.goal_id'], ),
    sa.ForeignKeyConstraint(['initiative_lead_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('initiative_id')
    )
    op.create_index(op.f('ix_strategic_initiatives_initiative_id'), 'strategic_initiatives', ['initiative_id'], unique=False)
    op.create_table('asset_business_alignment',
    sa.Column('alignment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('business_goal_id', sa.Integer(), nullable=True),
    sa.Column('contribution_level', sa.String(length=20), nullable=True),
    sa.Column('value_delivered', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['business_goal_id'], ['business_goals.goal_id'], ),
    sa.PrimaryKeyConstraint('alignment_id')
    )
    op.create_index(op.f('ix_asset_business_alignment_alignment_id'), 'asset_business_alignment', ['alignment_id'], unique=False)
    op.create_table('asset_vendor_mapping',
    sa.Column('mapping_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=100), nullable=True),
    sa.Column('monthly_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.vendor_id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_index(op.f('ix_asset_vendor_mapping_mapping_id'), 'asset_vendor_mapping', ['mapping_id'], unique=False)
    op.create_table('business_use_cases',
    sa.Column('use_case_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('use_case_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_value', sa.Text(), nullable=True),
    sa.Column('stakeholder_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.stakeholder_id'], ),
    sa.PrimaryKeyConstraint('use_case_id')
    )
    op.create_index(op.f('ix_business_use_cases_use_case_id'), 'business_use_cases', ['use_case_id'], unique=False)
    op.create_table('change_requests',
    sa.Column('change_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('impact_assessment', sa.Text(), nullable=True),
    sa.Column('rollback_plan', sa.Text(), nullable=True),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('approver_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approval_comments', sa.Text(), nullable=True),
    sa.Column('implementation_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('release_version', sa.String(length=50), nullable=True),
    sa.CheckConstraint("approval_status IN ('Pending', 'Approved', 'Rejected')", name='check_approval_status'),
    sa.CheckConstraint("change_type IN ('Modify', 'Deploy', 'Decommission', 'Config')", name='check_change_type'),
    sa.CheckConstraint("risk_level IN ('Low', 'Medium', 'High', 'Critical')", name='check_risk_level'),
    sa.CheckConstraint("status IN ('Submitted', 'InProgress', 'Completed', 'RolledBack')", name='check_status'),
    sa.ForeignKeyConstraint(['approver_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_index(op.f('ix_change_requests_approval_status'), 'change_requests', ['approval_status'], unique=False)
    op.create_index(op.f('ix_change_requests_asset_id'), 'change_requests', ['asset_id'], unique=False)
    op.create_index(op.f('ix_change_requests_change_id'), 'change_requests', ['change_id'], unique=False)
    op.create_index(op.f('ix_change_requests_risk_level'), 'change_requests', ['risk_level'], unique=False)
    op.create_table('compliance_violations',
    sa.Column('violation_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.CheckConstraint("severity IN ('Low', 'Medium', 'High')", name='check_severity'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('violation_id')
    )
    op.create_index(op.f('ix_compliance_violations_asset_id'), 'compliance_violations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_compliance_violations_violation_id'), 'compliance_violations', ['violation_id'], unique=False)
    op.create_index(op.f('ix_compliance_violations_violation_type'), 'compliance_violations', ['violation_type'], unique=False)
    op.create_table('initiative_deliverables',
    sa.Column('deliverable_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('initiative_id', sa.Integer(), nullable=True),
    sa.Column('deliverable_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['strategic_initiatives.initiative_id'], ),
    sa.PrimaryKeyConstraint('deliverable_id')
    )
    op.create_index(op.f('ix_initiative_deliverables_deliverable_id'), 'initiative_deliverables', ['deliverable_id'], unique=False)
    op.create_table('lifecycle_history',
    sa.Column('history_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=True),
    sa.Column('to_state', sa.String(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_lifecycle_history_asset_id'), 'lifecycle_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_lifecycle_history_changed_at'), 'lifecycle_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_lifecycle_history_history_id'), 'lifecycle_history', ['history_id'], unique=False)
    op.create_table('stakeholder_data_needs',
    sa.Column('need_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stakeholder_id', sa.Integer(), nullable=True),
    sa.Column('need_description', sa.Text(), nullable=False),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('related_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['related_asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['stakeholder_id'], ['stakeholders.stakeholder_id'], ),
    sa.PrimaryKeyConstraint('need_id')
    )
    op.create_index(op.f('ix_stakeholder_data_needs_need_id'), 'stakeholder_data_needs', ['need_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stakeholder_data_needs_need_id'), table_name='stakeholder_data_needs')
    op.drop_table('stakeholder_data_needs')
    op.drop_index(op.f('ix_lifecycle_history_history_id'), table_name='lifecycle_history')
    op.drop_index(op.f('ix_lifecycle_history_changed_at'), table_name='lifecycle_history')
    op.drop_index(op.f('ix_lifecycle_history_asset_id'), table_name='lifecycle_history')
    op.drop_table('lifecycle_history')
    op.drop_index(op.f('ix_initiative_deliverables_deliverable_id'), table_name='initiative_deliverables')
    op.drop_table('initiative_deliverables')
    op.drop_index(op.f('ix_compliance_violations_violation_type'), table_name='compliance_violations')
    op.drop_index(op.f('ix_compliance_violations_violation_id'), table_name='compliance_violations')
    op.drop_index(op.f('ix_compliance_violations_asset_id'), table_name='compliance_violations')
    op.drop_table('compliance_violations')
    op.drop_index(op.f('ix_change_requests_risk_level'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_change_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_asset_id'), table_name='change_requests')
    op.drop_index(op.f('ix_change_requests_approval_status'), table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index(op.f('ix_business_use_cases_use_case_id'), table_name='business_use_cases')
    op.drop_table('business_use_cases')
    op.drop_index(op.f('ix_asset_vendor_mapping_mapping_id'), table_name='asset_vendor_mapping')
    op.drop_table('asset_vendor_mapping')
    op.drop_index(op.f('ix_asset_business_alignment_alignment_id'), table_name='asset_business_alignment')
    op.drop_table('asset_business_alignment')
    op.drop_index(op.f('ix_strategic_initiatives_initiative_id'), table_name='strategic_initiatives')
    op.drop_table('strategic_initiatives')
    op.drop_index(op.f('ix_budget_allocations_budget_id'), table_name='budget_allocations')
    op.drop_table('budget_allocations')
    op.drop_index(op.f('ix_assets_naming_compliant'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_domains_domain_id'), table_name='domains')
    op.drop_table('domains')
    op.drop_index(op.f('ix_business_goals_goal_id'), table_name='business_goals')
    op.drop_table('business_goals')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_vendor_slas_sla_id'), table_name='vendor_slas')
    op.drop_table('vendor_slas')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_vendors_vendor_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_stakeholders_stakeholder_id'), table_name='stakeholders')
    op.drop_table('stakeholders')
    op.drop_index(op.f('ix_roles_role_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_compliance_metrics_metric_id'), table_name='compliance_metrics')
    op.drop_index(op.f('ix_compliance_metrics_metric_date'), table_name='compliance_metrics')
    op.drop_table('compliance_metrics')
    # ### end Alembic commands ###
